[features]
seeds = false
skip-lint = false
[programs.localnet]
auto_emissions = "5mji6qebN63LgPLLLUt5byc8R2Tq8vr1LakRz9cZmB8y"
[programs.devnet]
auto_emissions = "5mji6qebN63LgPLLLUt5byc8R2Tq8vr1LakRz9cZmB8y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ska/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
